# blog_writer.py - BlogWriter Module for ClawForge

"""
ClawForge - BlogWriter Module
==============================
Supports all 8 blog types:
  1. SEO Blog
  2. Listicle
  3. Product Comparison
  4. How-To Guide
  5. Landing Page
  6. Case Study
  7. Newsletter
  8. LinkedIn Post

Full pipeline:
  keyword research → outline → draft → SEO optimization
  → proofread → WordPress formatting → DOCX export

Every output includes:
  - Title options (3)
  - Meta description
  - H1 / H2 / H3 structure
  - FAQs section
  - Internal link suggestions
  - CTA (Call to Action)
"""

import os
import json
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Any, List

# ============================================================================
# BLOG TYPES
# ============================================================================

BLOG_TYPES = [
    "seo_blog",
    "listicle",
    "product_comparison",
    "how_to_guide",
    "landing_page",
    "case_study",
    "newsletter",
    "linkedin_post",
]

# ============================================================================
# BLOG OUTPUT CLASS
# ============================================================================

class BlogOutput:
    """Represents a complete blog output with all SEO elements."""
    
    def __init__(
        self,
        blog_type: str,
        keyword: str,
        title_options: List[str],
        meta_description: str,
        outline: Dict[str, Any],
        draft: str,
        faqs: List[Dict[str, str]],
        internal_links: List[str],
        cta: str,
        wordpress_ready: str = "",
    ):
        self.blog_type = blog_type
        self.keyword = keyword
        self.title_options = title_options
        self.meta_description = meta_description
        self.outline = outline
        self.draft = draft
        self.faqs = faqs
        self.internal_links = internal_links
        self.cta = cta
        self.wordpress_ready = wordpress_ready
        self.created_at = datetime.utcnow().isoformat()

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "blog_type": self.blog_type,
            "keyword": self.keyword,
            "title_options": self.title_options,
            "meta_description": self.meta_description,
            "outline": self.outline,
            "draft": self.draft,
            "faqs": self.faqs,
            "internal_links": self.internal_links,
            "cta": self.cta,
            "word_count": len(self.draft.split()),
            "created_at": self.created_at,
        }

    def to_markdown(self) -> str:
        """Full markdown export with all SEO elements."""
        lines = [
            f"# {self.title_options[0]}",
            f"\n> **Meta Description:** {self.meta_description}\n",
            f"**Keyword:** `{self.keyword}`  |  **Type:** `{self.blog_type}`  |  **Words:** `{len(self.draft.split())}`\n",
            "---\n",
            self.draft,
            "\n\n---\n",
            "## Frequently Asked Questions\n",
        ]
        for faq in self.faqs:
            lines.append(f"**Q: {faq['q']}**")
            lines.append(f"A: {faq['a']}\n")

        lines += [
            "\n---\n",
            f"## Call to Action\n{self.cta}\n",
            "---\n",
            "## Internal Link Suggestions\n",
        ]
        for link in self.internal_links:
            lines.append(f"- {link}")

        lines += [
            "\n---\n",
            "## Alternative Titles\n",
        ]
        for i, t in enumerate(self.title_options, 1):
            lines.append(f"{i}. {t}")

        lines.append(f"\n\n_Generated by ClawForge BlogWriter — {self.created_at}_")
        return "\n".join(lines)

    def to_wordpress_html(self) -> str:
        """Return WordPress-compatible HTML."""
        if self.wordpress_ready:
            return self.wordpress_ready
        return self._markdown_to_html(self.to_markdown())

    def _markdown_to_html(self, markdown: str) -> str:
        """Simple markdown to HTML conversion."""
        lines = markdown.split("\n")
        html = []
        for line in lines:
            if line.startswith("# "):
                html.append(f'<h1>{line[2:]}</h1>')
            elif line.startswith("## "):
                html.append(f'<h2>{line[3:]}</h2>')
            elif line.startswith("### "):
                html.append(f'<h3>{line[4:]}</h3>')
            elif line.startswith("- ") or line.startswith("* "):
                html.append(f'<li>{line[2:]}</li>')
            elif line.strip():
                html.append(f'<p>{line}</p>')
        return "\n".join(html)

# ============================================================================
# BLOG WRITER CLASS
# ============================================================================

class BlogWriter:
    """
    Generates production-ready blog content for all 8 blog types.
    When connected to OllamaClient, uses llama3/mistral for generation.
    In standalone mode, generates structured templates.
    """
    
    def __init__(self, ollama_client=None):
        """
        Initialize BlogWriter.
        
        Args:
            ollama_client: Optional OllamaClient instance for LLM generation
        """
        self.ollama = ollama_client
        
        # Import workspace paths
        try:
            from backend.identity import WORKSPACE_PATHS
            self.workspace_paths = WORKSPACE_PATHS
        except ImportError:
            self.workspace_paths = {
                "output": "./workspace/output",
                "tasks": "./workspace/tasks"
            }
    
    # ============================================================================
    # STEP 1: KEYWORD RESEARCH
    # ============================================================================
    
    def keyword_research(self, topic: str) -> Dict[str, Any]:
        """
        Generates keyword strategy for the topic.
        
        Args:
            topic: The main topic for the blog
        
        Returns:
            Dictionary with keyword research data
        """
        words = topic.lower().split()
        primary = topic
        secondary = [
            f"best {topic}",
            f"how to use {topic}",
            f"{topic} guide",
            f"{topic} tips",
            f"{topic} for beginners",
        ]
        long_tail = [
            f"what is {topic} and how does it work",
            f"top {topic} tools in {datetime.utcnow().year}",
            f"{topic} complete guide for small businesses",
        ]
        return {
            "primary_keyword": primary,
            "secondary_keywords": secondary,
            "long_tail_keywords": long_tail,
            "suggested_word_count": 1500,
            "target_audience": "General / Small Business Owners",
        }
    
    # ============================================================================
    # STEP 2: OUTLINE CREATION
    # ============================================================================
    
    def create_outline(self, blog_type: str, keyword: str, topic: str) -> Dict[str, Any]:
        """
        Creates H1/H2/H3 structured outline based on blog type.
        
        Args:
            blog_type: Type of blog post
            keyword: Primary keyword
            topic: Blog topic
        
        Returns:
            Dictionary with H1, H2, H3 structure
        """
        year = datetime.utcnow().year
        
        outlines = {
            "seo_blog": {
                "H1": f"The Ultimate Guide to {topic}",
                "H2": [
                    f"What is {topic}?",
                    f"Why {topic} Matters in {year}",
                    f"Top Benefits of {topic}",
                    f"How to Get Started with {topic}",
                    f"Common Mistakes to Avoid",
                    f"Expert Tips for Success",
                    "Conclusion",
                ],
                "H3": {
                    f"What is {topic}?": ["Definition", "Brief History", "Key Features"],
                    f"Top Benefits of {topic}": ["Benefit 1", "Benefit 2", "Benefit 3"],
                    "How to Get Started with {topic}": ["Step 1", "Step 2", "Step 3"],
                }
            },
            "listicle": {
                "H1": f"15 Best {topic} Tools You Need in {year}",
                "H2": [f"#{i+1} - Tool Name" for i in range(10)] + ["Final Thoughts"],
                "H3": {}
            },
            "how_to_guide": {
                "H1": f"How to {topic}: Step-by-Step Guide",
                "H2": ["What You'll Need", "Step 1: Getting Started",
                        "Step 2: Core Process", "Step 3: Advanced Tips",
                        "Troubleshooting", "Final Results"],
                "H3": {}
            },
            "product_comparison": {
                "H1": f"{topic}: Which Option Is Right for You?",
                "H2": ["Overview", "Feature Comparison", "Pricing",
                        "Pros and Cons", "Our Verdict"],
                "H3": {}
            },
            "case_study": {
                "H1": f"How [Company] Used {topic} to Achieve [Result]",
                "H2": ["The Challenge", "Our Solution", "Implementation",
                        "Results & Metrics", "Key Takeaways"],
                "H3": {}
            },
            "landing_page": {
                "H1": f"Transform Your Business with {topic}",
                "H2": ["Why Choose Us", "Key Features", "Pricing",
                        "Testimonials", "FAQ", "Get Started Today"],
                "H3": {}
            },
            "newsletter": {
                "H1": f"This Week in {topic}: What You Need to Know",
                "H2": ["Top Story", "Industry News", "Tips of the Week",
                        "Tools We Love", "Upcoming Events"],
                "H3": {}
            },
            "linkedin_post": {
                "H1": f"[Hook] about {topic}",
                "H2": ["The Problem", "The Insight", "The Solution", "CTA"],
                "H3": {}
            },
        }
        return outlines.get(blog_type, outlines["seo_blog"])
    
    # ============================================================================
    # STEP 3: DRAFT WRITING
    # ============================================================================
    
    def write_draft(self, blog_type: str, topic: str, keyword: str, 
                   outline: Dict[str, Any], tone: str = "professional") -> str:
        """
        Generates the full blog draft.
        
        Args:
            blog_type: Type of blog
            topic: Blog topic
            keyword: Primary keyword
            outline: Blog outline
            tone: Writing tone
        
        Returns:
            Complete blog draft as string
        """
        # Use Ollama if connected
        if self.ollama:
            prompt = self._build_llm_prompt(blog_type, topic, keyword, outline, tone)
            result = self.ollama.route_and_generate(prompt, "content_writing")
            if result.get("status") == "success":
                return result["response"]
        
        # Template-based fallback
        return self._template_draft(blog_type, topic, keyword, outline, tone)
    
    def _build_llm_prompt(self, blog_type: str, topic: str, keyword: str, 
                          outline: Dict[str, Any], tone: str) -> str:
        """Build prompt for LLM generation."""
        h2s = "\n".join(f"- {h}" for h in outline.get("H2", []))
        return f"""
You are an expert SEO content writer. Write a complete {blog_type.replace("_", " ")} 
about "{topic}" using the primary keyword "{keyword}".

Tone: {tone}
Structure:
{outline.get('H1', '')}
{h2s}

Requirements:
- Minimum 1200 words
- Use the keyword naturally 5-8 times
- Include specific data, examples, and actionable advice
- Write in clear, engaging paragraphs
- Do NOT use placeholder text

Write the full article now:
""".strip()
    
    def _template_draft(self, blog_type: str, topic: str, keyword: str, 
                       outline: Dict[str, Any], tone: str) -> str:
        """Generate a structured template draft."""
        h1 = outline.get("H1", f"The Complete Guide to {topic}")
        h2s = outline.get("H2", [])
        
        # LinkedIn post template
        if blog_type == "linkedin_post":
            return self._linkedin_template(topic, keyword)
        
        # Newsletter template
        if blog_type == "newsletter":
            return self._newsletter_template(topic, keyword, h2s)
        
        # Standard article format
        sections = [f"# {h1}\n"]
        
        intro = (
            f"In today's fast-paced world, understanding **{keyword}** is more important than ever. "
            f"Whether you're a seasoned professional or just getting started, this guide breaks down "
            f"everything you need to know about {topic} in a clear, actionable way.\n\n"
            f"By the end of this article, you'll have a solid grasp of {keyword}, "
            f"including best practices, common pitfalls, and proven strategies for success."
        )
        sections.append(intro)
        
        for h2 in h2s:
            sections.append(f"\n\n## {h2}\n")
            
            h2_lower = h2.lower()
            
            if "what is" in h2_lower:
                sections.append(
                    f"**{topic}** refers to the practice or concept of leveraging {keyword} "
                    f"to achieve specific goals. At its core, it encompasses a set of strategies, "
                    f"tools, and methodologies designed to maximize efficiency and results.\n\n"
                    f"### Key Characteristics\n"
                    f"- **Scalability**: Works for businesses of all sizes\n"
                    f"- **Flexibility**: Adapts to different industries and use cases\n"
                    f"- **Measurability**: Results can be tracked and optimized\n"
                )
            elif "benefit" in h2_lower or "why" in h2_lower:
                sections.append(
                    f"Understanding the benefits of {keyword} can help you make informed decisions. "
                    f"Here are the top reasons professionals are turning to {topic}:\n\n"
                    f"### Benefit 1: Increased Efficiency\n"
                    f"By automating repetitive tasks and streamlining workflows, {topic} saves "
                    f"significant time and resources.\n\n"
                    f"### Benefit 2: Better Results\n"
                    f"Organizations using {keyword} report measurable improvements in output quality.\n\n"
                    f"### Benefit 3: Competitive Advantage\n"
                    f"Staying ahead of industry trends with {topic} positions you as a leader.\n"
                )
            elif "how to" in h2_lower or "started" in h2_lower or "step" in h2_lower:
                sections.append(
                    f"Getting started with {keyword} doesn't have to be overwhelming. "
                    f"Follow these steps:\n\n"
                    f"**Step 1: Define Your Goals**\n"
                    f"Before diving into {topic}, clarify what success looks like for you.\n\n"
                    f"**Step 2: Choose the Right Tools**\n"
                    f"Research platforms and tools that support {keyword}.\n\n"
                    f"**Step 3: Implement and Iterate**\n"
                    f"Start small, measure results, and refine your approach.\n"
                )
            elif "mistake" in h2_lower or "avoid" in h2_lower:
                sections.append(
                    f"Even experienced professionals make mistakes with {keyword}. "
                    f"Here's what to watch out for:\n\n"
                    f"**Mistake 1: Skipping the Planning Phase**\n"
                    f"Jumping straight into implementation without a clear strategy.\n\n"
                    f"**Mistake 2: Ignoring Analytics**\n"
                    f"Data is your best friend for optimization.\n\n"
                    f"**Mistake 3: Underestimating the Learning Curve**\n"
                    f"{topic} takes time to master.\n"
                )
            elif "tip" in h2_lower or "expert" in h2_lower:
                sections.append(
                    f"Ready to take your {keyword} game to the next level?\n\n"
                    f"- **Stay Updated**: The {topic} landscape evolves fast.\n"
                    f"- **Join Communities**: Connect with others in your field.\n"
                    f"- **Document Everything**: Keep detailed records.\n"
                    f"- **Test Constantly**: A/B test your approaches.\n"
                )
            elif "conclusion" in h2_lower or "final" in h2_lower:
                sections.append(
                    f"{topic} is a powerful approach that, when implemented correctly, "
                    f"can transform the way you work and the results you achieve.\n\n"
                    f"Start today — even small steps toward mastering {keyword} can lead to "
                    f"significant long-term gains."
                )
            else:
                sections.append(
                    f"When it comes to {h2.lower()}, {topic} offers unique advantages. "
                    f"By focusing on {keyword}, professionals can unlock new levels of performance.\n"
                )
        
        return "\n".join(sections)
    
    def _linkedin_template(self, topic: str, keyword: str) -> str:
        """Generate LinkedIn post template."""
        return (
            f"Most people get {topic} completely wrong.\n\n"
            f"Here's what the top 1% know that others don't:\n\n"
            f"I spent months studying how the best teams use {keyword}.\n\n"
            f"What I found was surprising:\n\n"
            f"1. It's not about working harder\n"
            f"2. It's not about having the best tools\n"
            f"3. It's about understanding the core principles\n\n"
            f"The professionals who excel at {keyword} share 3 traits:\n\n"
            f"- They start with clear goals\n"
            f"- They measure everything\n"
            f"- They iterate relentlessly\n\n"
            f"If you're struggling with {topic}, ask yourself:\n"
            f"Are you doing these 3 things consistently?\n\n"
            f"Drop a comment below if this resonates.\n\n"
            f"Follow me for more insights on {keyword}.\n\n"
            f"#{topic.replace(' ', '')} #{keyword.replace(' ', '')}"
        )
    
    def _newsletter_template(self, topic: str, keyword: str, h2s: List[str]) -> str:
        """Generate newsletter template."""
        return (
            f"**Subject: This Week in {topic} - Do Not Miss These Updates**\n\n"
            f"Hi [First Name],\n\n"
            f"Welcome back to your weekly {topic} digest. This week we're covering "
            f"everything you need to stay ahead in {keyword}.\n\n"
            f"## Top Story\n"
            f"[Insert top industry news about {topic}]\n\n"
            f"## Tip of the Week\n"
            f"When working with {keyword}, always start with a clear outcome in mind.\n\n"
            f"## Tool We Love\n"
            f"[Recommended tool related to {topic}]\n\n"
            f"## Upcoming Events\n"
            f"- Webinar: Mastering {topic} - [Date]\n"
            f"- Conference: {keyword} Summit - [Date]\n\n"
            f"Until next week,\n[Your Name]"
        )
    
    # ============================================================================
    # STEP 4: SEO OPTIMIZATION
    # ============================================================================
    
    def seo_optimize(self, draft: str, keyword: str) -> Dict[str, Any]:
        """
        Analyzes and reports SEO metrics of the draft.
        
        Args:
            draft: Blog draft content
            keyword: Primary keyword
        
        Returns:
            Dictionary with SEO metrics
        """
        words = draft.split()
        word_count = len(words)
        keyword_count = draft.lower().count(keyword.lower())
        keyword_density = round((keyword_count / word_count) * 100, 2) if word_count else 0
        
        density_status = "Good" if 1.0 <= keyword_density <= 3.0 else "Adjust"
        
        return {
            "word_count": word_count,
            "keyword": keyword,
            "keyword_occurrences": keyword_count,
            "keyword_density_percent": keyword_density,
            "recommended_density": "1.5-2.5%",
            "density_status": density_status,
            "has_h1": "# " in draft,
            "has_h2": "## " in draft,
            "has_h3": "### " in draft,
            "readability": "Good" if word_count > 600 else "Too Short",
        }
    
    # ============================================================================
    # STEP 5: GENERATE FAQS
    # ============================================================================
    
    def generate_faqs(self, topic: str, keyword: str) -> List[Dict[str, str]]:
        """
        Generate FAQ section for the blog.
        
        Args:
            topic: Blog topic
            keyword: Primary keyword
        
        Returns:
            List of FAQ dictionaries
        """
        return [
            {
                "q": f"What is {topic}?",
                "a": f"{topic} is a methodology/approach that helps individuals and organizations "
                     f"achieve better outcomes by leveraging {keyword} effectively."
            },
            {
                "q": f"How long does it take to learn {keyword}?",
                "a": f"Most people can grasp the basics of {keyword} within a few weeks, "
                     f"while mastery typically takes 3-6 months of consistent practice."
            },
            {
                "q": f"Is {topic} right for small businesses?",
                "a": f"Absolutely. {topic} scales to fit businesses of all sizes, making it "
                     f"an excellent investment for small businesses looking to grow efficiently."
            },
            {
                "q": f"What are the best tools for {keyword}?",
                "a": f"The best tools depend on your specific goals, but popular options include "
                     f"industry-leading platforms designed around {topic}."
            },
            {
                "q": f"How do I measure success with {keyword}?",
                "a": f"Track KPIs aligned with your goals - such as productivity metrics, "
                     f"ROI, engagement rates, or conversion rates depending on your use case."
            },
        ]
    
    # ============================================================================
    # STEP 6: INTERNAL LINKS + CTA
    # ============================================================================
    
    def generate_internal_links(self, topic: str) -> List[str]:
        """
        Generate internal link suggestions.
        
        Args:
            topic: Blog topic
        
        Returns:
            List of internal link URLs
        """
        topic_slug = topic.lower().replace(' ', '-')
        return [
            f"/blog/getting-started-with-{topic_slug}",
            f"/blog/{topic_slug}-best-practices",
            f"/resources/{topic_slug}-tools",
            f"/case-studies/{topic_slug}-success-stories",
            f"/guides/advanced-{topic_slug}",
        ]
    
    def generate_cta(self, topic: str, blog_type: str) -> str:
        """
        Generate call-to-action based on blog type.
        
        Args:
            topic: Blog topic
            blog_type: Type of blog
        
        Returns:
            CTA string
        """
        ctas = {
            "seo_blog": f"Ready to master {topic}? Download our free checklist and start implementing today. [Get Free Guide]",
            "listicle": f"Which tool is your favorite? Share in the comments and subscribe for more {topic} roundups.",
            "how_to_guide": f"Now it's your turn! Start your {topic} journey today and share your results with us.",
            "product_comparison": f"Still not sure which is right for you? Book a free consultation with our experts.",
            "case_study": f"Want results like these? Let's talk about how we can help your business with {topic}.",
            "landing_page": f"Start your free trial today - no credit card required. [Get Started]",
            "newsletter": f"Know someone who would love this? Forward this email and help them stay ahead.",
            "linkedin_post": f"Follow me for weekly insights on {topic}. And share this if it helped you!",
        }
        return ctas.get(blog_type, f"Start your {topic} journey today. [Learn More]")
    
    # ============================================================================
    # STEP 7: WORDPRESS HTML EXPORT
    # ============================================================================
    
    def to_wordpress_html(self, markdown_content: str) -> str:
        """
        Converts markdown to WordPress-compatible HTML blocks.
        
        Args:
            markdown_content: Markdown content
        
        Returns:
            WordPress HTML string
        """
        lines = markdown_content.split("\n")
        html = []
        
        for line in lines:
            if line.startswith("# "):
                html.append(f'<!-- wp:heading -->\n<h1>{line[2:]}</h1>\n<!-- /wp:heading -->')
            elif line.startswith("## "):
                html.append(f'<!-- wp:heading -->\n<h2>{line[3:]}</h2>\n<!-- /wp:heading -->')
            elif line.startswith("### "):
                html.append(f'<!-- wp:heading -->\n<h3>{line[4:]}</h3>\n<!-- /wp:heading -->')
            elif line.startswith("- ") or line.startswith("* "):
                html.append(f'<li>{line[2:]}</li>')
            elif line.strip():
                html.append(f'<p>{line}</p>')
        
        return "\n".join(html)
    
    # ============================================================================
    # MASTER PIPELINE
    # ============================================================================
    
    def run_pipeline(
        self,
        topic: str,
        blog_type: str = "seo_blog",
        keyword: str = None,
        tone: str = "professional",
        task_id: str = "blog_task",
        save_outputs: bool = True,
    ) -> BlogOutput:
        """
        Full blog pipeline:
        keyword research → outline → draft → SEO optimize
        → FAQs → links → CTA → WordPress format → save
        
        Args:
            topic: Blog topic
            blog_type: Type of blog post
            keyword: Primary keyword (optional, defaults to topic)
            tone: Writing tone
            task_id: Task ID for saving outputs
            save_outputs: Whether to save to disk
        
        Returns:
            BlogOutput object
        """
        if blog_type not in BLOG_TYPES:
            raise ValueError(f"Invalid blog_type. Choose from: {BLOG_TYPES}")
        
        keyword = keyword or topic
        
        print(f"\n[OK] BlogWriter Pipeline: [{blog_type}] - '{topic}'")
        
        # Step 1: Keyword research
        print("  [1/7] Keyword research...")
        kw_data = self.keyword_research(topic)
        
        # Step 2: Outline
        print("  [2/7] Creating outline...")
        outline = self.create_outline(blog_type, keyword, topic)
        
        # Step 3: Draft
        print("  [3/7] Writing draft...")
        draft = self.write_draft(blog_type, topic, keyword, outline, tone)
        
        # Step 4: SEO check
        print("  [4/7] SEO optimization...")
        seo = self.seo_optimize(draft, keyword)
        print(f"         Words: {seo['word_count']} | Density: {seo['keyword_density_percent']}%")
        
        # Step 5: FAQs
        print("  [5/7] Generating FAQs...")
        faqs = self.generate_faqs(topic, keyword)
        
        # Step 6: Links + CTA
        print("  [6/7] Internal links + CTA...")
        links = self.generate_internal_links(topic)
        cta = self.generate_cta(topic, blog_type)
        
        # Title options
        title_options = [
            outline.get("H1", f"The Complete Guide to {topic}"),
            f"Everything You Need to Know About {topic} in {datetime.utcnow().year}",
            f"{topic}: A Comprehensive Guide for Beginners and Experts",
        ]
        
        # Meta description
        meta = (
            f"Discover everything about {keyword}. This comprehensive guide covers "
            f"what {topic} is, why it matters, how to get started, and expert tips "
            f"for success. Read now to transform your approach."
        )[:160]
        
        # Step 7: WordPress format
        print("  [7/7] Formatting for WordPress...")
        markdown_content = BlogOutput(
            blog_type, keyword, title_options, meta, outline,
            draft, faqs, links, cta, ""
        ).to_markdown()
        wp_html = self.to_wordpress_html(markdown_content)
        
        # Create output object
        output = BlogOutput(
            blog_type=blog_type,
            keyword=keyword,
            title_options=title_options,
            meta_description=meta,
            outline=outline,
            draft=draft,
            faqs=faqs,
            internal_links=links,
            cta=cta,
            wordpress_ready=wp_html,
        )
        
        # Save outputs
        if save_outputs:
            self._save_outputs(output, task_id)
        
        return output
    
    def _save_outputs(self, output: BlogOutput, task_id: str):
        """Save blog outputs to workspace."""
        output_dir = Path(self.workspace_paths["output"]) / task_id
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Save markdown
        (output_dir / "blog.md").write_text(output.to_markdown(), encoding='utf-8')
        
        # Save WordPress HTML
        (output_dir / "blog_wordpress.html").write_text(output.to_wordpress_html(), encoding='utf-8')
        
        # Save metadata
        (output_dir / "blog_meta.json").write_text(
            json.dumps(output.to_dict(), indent=2), 
            encoding='utf-8'
        )
        
        print(f"  [OK] Saved to {output_dir}")

# ============================================================================
# CONVENIENCE FUNCTION
# ============================================================================

def create_blog(
    topic: str,
    blog_type: str = "seo_blog",
    keyword: str = None,
    tone: str = "professional",
    task_id: str = "blog_task",
    ollama_client = None,
) -> BlogOutput:
    """
    Convenience function to create a blog post.
    
    Args:
        topic: Blog topic
        blog_type: Type of blog
        keyword: Primary keyword
        tone: Writing tone
        task_id: Task ID
        ollama_client: Optional OllamaClient
    
    Returns:
        BlogOutput object
    """
    writer = BlogWriter(ollama_client=ollama_client)
    return writer.run_pipeline(topic, blog_type, keyword, tone, task_id)

# ============================================================================
# TEST
# ============================================================================

if __name__ == "__main__":
    writer = BlogWriter()
    
    print("=" * 60)
    print("  BlogWriter - Full Pipeline Test")
    print("=" * 60)
    
    # Test SEO blog
    output = writer.run_pipeline(
        topic="AI tools for small businesses",
        blog_type="seo_blog",
        keyword="AI tools for small businesses",
        tone="professional",
        task_id="test_blog_001",
    )
    
    print(f"\n[OK] Output Summary:")
    print(f"  Title: {output.title_options[0][:60]}...")
    print(f"  Meta:  {output.meta_description[:60]}...")
    print(f"  Words: {len(output.draft.split())}")
    print(f"  FAQs:  {len(output.faqs)}")
    
    # Test LinkedIn post
    print("\n" + "-" * 60)
    print("  LinkedIn Post Test")
    print("-" * 60)
    li = writer.run_pipeline(
        topic="productivity",
        blog_type="linkedin_post",
        task_id="test_linkedin_001",
    )
    print(li.draft[:400] + "...")
