"""
TestFastAPI - FastAPI Backend
Generated by ClawForge
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, List
import uvicorn

app = FastAPI(title="TestFastAPI", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# Models

class Item(BaseModel):
    id: Optional[int] = None
    name: str
    description: Optional[str] = None


# In-memory store

items: List[Item] = []


# Routes

@app.get("/")
async def root():
    return {"status": "ok", "service": "TestFastAPI"}


@app.get("/api/items")
async def get_items():
    return {"items": items, "count": len(items)}


@app.post("/api/items")
async def create_item(item: Item):
    item.id = len(items) + 1
    items.append(item)
    return {"status": "created", "item": item}


@app.get("/api/items/{item_id}")
async def get_item(item_id: int):
    for item in items:
        if item.id == item_id:
            return item
    raise HTTPException(status_code=404, detail="Item not found")


@app.delete("/api/items/{item_id}")
async def delete_item(item_id: int):
    global items
    items = [i for i in items if i.id != item_id]
    return {"status": "deleted"}


if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
